Message display rules configurator improvements
th2-net/th2-rpt-viewer pull request #143
Opened 2021-04-07 11:29 UTC by VitalyMashanov

2021-04-15 10:33 UTC, rzvdv commented on src/hooks/useDimensions.ts
> +function useDimensions<T extends HTMLElement>(live?: boolean): [RefObject<T>, DOMRect | null] {
is it even used anywhere?

2021-04-15 10:39 UTC, VitalyMashanov commented on src/hooks/useDimensions.ts
> +function useDimensions<T extends HTMLElement>(live?: boolean): [RefObject<T>, DOMRect | null] {
at RuleEditor.tsx

2021-04-15 16:10 UTC, rzvdv requested changes

2021-04-15 16:10 UTC, rzvdv commented on src/components/messages-view-configurator/EditableSortOrderItem.tsx
> +		<>
I think you are overusing fragments. They have their specific use case. But i see fragments in almost every component in this pr

2021-04-15 16:10 UTC, rzvdv commented on src/components/messages-view-configurator/NewRule.tsx
> +		const hasSame =
`rulesStore.setNewMessagesDisplayRule` already has a 'hasSame' check

2021-04-15 16:10 UTC, rzvdv commented on src/components/messages-view-configurator/NewSortOrderItem.tsx
> +		const hasSame = sortOrder.sortOrder.findIndex(({ item }) => item === newItem) !== -1;
sortOrder.setNewItem already has a 'hasSame' check

2021-04-15 16:10 UTC, rzvdv commented on src/components/messages-view-configurator/RuleRow.tsx
> +const RuleRow: React.FC<RuleRowProps> = props => {
We dont use this kind of typing for component, lets make our code consistent

2021-04-15 16:10 UTC, rzvdv commented on src/components/messages-view-configurator/RuleRow.tsx
> +	const renderRow = () => {
this render function is unnecessary

2021-04-15 16:10 UTC, rzvdv commented on src/components/messages-view-configurator/RuleRow.tsx
> +	};
Empty lines in code make it more readable

2021-04-15 16:10 UTC, rzvdv commented on src/stores/MessageBodySortStore.ts
> +		const hasSame = this.sortOrder.find(existed => existed === orderItem);
if object reference is consistent you can you just `includes`

2021-05-13 09:23 UTC, rzvdv commented on src/components/message/message-card/MessageBodyCard.tsx
> +	const sortOrderItems = sortOrder.map(item => item.item);
look like this is a case for computed value

2021-05-13 09:23 UTC, rzvdv commented on src/components/message/message-card/MessageBodyCard.tsx
> +	const fields = getSortedFields(body ? body.fields : {}, sortOrderItems);
it this value can be memoized

2021-05-13 09:24 UTC, rzvdv commented on src/components/message/message-card/MessageBodyCard.tsx
> +	const sortOrderItems = sortOrder.map(item => item.item);
you are receiving it as a prop primarySort: string[];

2021-05-13 09:26 UTC, rzvdv commented on src/components/messages-view-configurator/BodySortConfig.tsx
> +	const sortOrder = useMessageBodySortStore();
sortOrderStore ?

2021-05-13 09:29 UTC, rzvdv commented on src/components/messages-view-configurator/MessagesViewConfigurator.tsx
> +							<i>You can use * character to match an unknown substring as part of session name</i>
i think it's better if sentence Starts with Use, omit you can

2021-05-13 09:31 UTC, rzvdv commented on src/components/messages-view-configurator/NewRule.tsx
> +				disabled={session === ''}>
!session.trim()

2021-05-13 09:31 UTC, rzvdv commented on src/components/messages-view-configurator/NewSortOrderItem.tsx
> +				disabled={newItem === ''}>
`!newItem.trim()`

2021-05-13 09:33 UTC, rzvdv commented on src/components/messages-view-configurator/Reorder.tsx
> +	isFirst: boolean | null;
i think its better to have isFirst as optional value that defaults to `false`.

2021-05-24 12:29 UTC, rzvdv commented on src/components/message/message-card/MessageBodyCard.tsx
> +		!isSimpleValue(field) && !isListValue(field)
lets create helper function isMessageValueField

we can also memoize `sortedSubFields` since we memoized it in MessageBodyCard

2021-05-24 12:32 UTC, rzvdv commented on src/components/messages-view-configurator/EditableRule.tsx
> +		return sessionIsEditing && rule.editableSession ? (
lets refactor these render functions to components inside this file Session and ViewType

2021-05-24 12:33 UTC, rzvdv commented on src/components/messages-view-configurator/EditableSortOrderItem.tsx
> +		return itemIsEditing ? (
lets delete render function and move this inside render

2021-05-24 14:29 UTC, rzvdv commented on src/stores/MessageDisplayRulesStore.ts
> +			if (rootDisplayRule.hasOwnProperty('fullyEditable')) {
this should have been done in indexeddb upgade, but lets leave this property for now

2021-05-24 14:31 UTC, rzvdv requested changes
lets submit session or message name on enter

2021-05-28 10:16 UTC, rzvdv approved these changes

2021-05-28 10:17 UTC, merged