Add load more button in search panel & add pausing and resuming search
th2-net/th2-rpt-viewer pull request #155
Opened 2021-04-15 10:25 UTC by icefleen

2021-04-21 10:01 UTC, YourWeebyNeighbor requested changes

2021-04-21 12:23 UTC, icefleen commented on src/components/search-panel/search-form/SearchSubmit.tsx
> +	})();
done: https://github.com/th2-net/th2-rpt-viewer/pull/155/commits/5bed2b83103b95b73abe40b964f05a414404bbac

2021-04-21 16:05 UTC, YourWeebyNeighbor submitted a review, later dismissed

2021-04-22 08:40 UTC, YourWeebyNeighbor approved these changes

2021-04-22 08:40 UTC, merged