[TH2-2533] Add attached messages selection to messages panel
th2-net/th2-rpt-viewer pull request #271
Opened 2021-10-25 10:29 UTC by osinkinroman

2021-11-01 12:40 UTC, osinkinroman commented
Layout from https://www.figma.com/file/vB9EyLv1GBE3vJqy2Hxk08/TH2-New-Report-Style-Updates?node-id=2498%3A66935

2021-11-02 07:34 UTC, osinkinroman commented
In Figma its in TimeLine and Serch page

2021-11-02 12:59 UTC, rzvdv requested changes

2021-11-02 12:59 UTC, rzvdv commented on src/components/message/MessagesAttachedSelection.tsx
> +import React from 'react';
add license

2021-11-02 12:59 UTC, rzvdv commented on src/components/message/MessagesAttachedSelection.tsx
> +		if (attachedMessages !== currentAttachedMessages) {
i think we dont even need to compare it, hook will be called every time we load new attached messages so we can delete state `currentAttachedMessages`

2021-11-03 15:10 UTC, rzvdv commented on src/components/message/MessagesAttachedSelection.tsx
> +			<span className='messages-list__attached-messages-text'>Show previous</span>
make text to be part of the button

2021-11-03 15:13 UTC, rzvdv commented on src/components/message/MessagesAttachedSelection.tsx
> +const MessageAttachedSelection = () => {
i think it should be AttachedMessageSelection

2021-11-16 13:33 UTC, rzvdv approved these changes

2021-11-16 13:38 UTC, merged